services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bonphyre_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/bonphyre
    networks:
      - bonphyre_network

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bonphyre_test
    env_file:
      - .env
    depends_on:
      - test_db
    volumes:
      - ./:/bonphyre
    networks:
      - bonphyre_network
    entrypoint: ["pytest", "--disable-warnings"]

  db:
    image: postgres:15
    container_name: postgres_db
    command: -p 5432
    restart: unless-stopped
    environment:
      PGUSER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-bonphyre}
      PGDATA: /data/postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bonphyre_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:15
    container_name: postgres_test_db
    command: -p 5432
    restart: unless-stopped
    environment:
      PGUSER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-bonphyre_test}
      PGDATA: /data/postgresql
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - bonphyre_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
  #   networks:
  #     - bonphyre_network

volumes:
  postgres_data:
  test_postgres_data:

networks:
  bonphyre_network:
    driver: bridge
